In [5]:
import pickle
import pandas as pd
import numpy as np
from autotest_exp import load_experiment_result, read_config, add_labels_to_result_dfs

In [2]:
config_file_path = './config.ini'
result_df = {}

In [6]:
config = read_config(config_file_path)
executions = ["Integration_Option_0","Integration_Option_1"]
result_dfs, results_per_table = load_experiment_result(executions, config)
result_dfs = add_labels_to_result_dfs(result_dfs)
for execution in results_per_table.keys():
    for run in results_per_table[execution].keys():
        results_per_table[execution][run] = pd.DataFrame(results_per_table[execution][run]).T
        results_per_table[execution][run]["total_cells"] = results_per_table[execution][run]["tp"] + results_per_table[execution][run]["fp"] + results_per_table[execution][run]["fn"] + results_per_table[execution][run]["tn"]
        results_per_table[execution][run] = results_per_table[execution][run].T
runs = list(result_dfs[executions[1]].keys())

In [19]:
comparison_dfs = {}
for run in runs:
    comparison_df = results_per_table[executions[1]][run].T
    diff_columns = ["tp", "fp", "fn", "tn", "precision", "recall", "f_score"]
    comparison_df[diff_columns] = results_per_table[executions[1]][run].T[diff_columns] - results_per_table[executions[0]][run].T[diff_columns]
    comparison_dfs[run] = comparison_df

In [48]:
foo = comparison_dfs[runs[2]]
print(foo[foo["table_name"] == "Rates_of_Preventable_Hospitalizations_for_Selected_Medical_Conditions_by_County_(LGHC_Indicator)"]["f_score"].sum())
foo = foo[foo["table_name"] != "Rates_of_Preventable_Hospitalizations_for_Selected_Medical_Conditions_by_County_(LGHC_Indicator)"]
#foo.plot.scatter(x="total_cells", y="f_score", logx=True)
foo["f_score"].sum() / 95

0.051480124318333126
-0.013233965318736884

0.052161325261881226

In [18]:
e, r = 1, 2
print(f"{executions[e]} - {runs[r]}")
foo = pd.DataFrame(result_dfs[executions[e]][runs[r]])
foo

Integration_Option_1 - _test_edbt_DGov_Typo_1152_labels

,column_group,table_id,table_name,table_shape,col_id,col_name,cell_idx,cell_value,predicted,label,auto_test_label,propagated_label,result,auto_test_overwrite
0,"(34, 0)",ff26cfb6b048749e7a435ed340d74230,Warden_Districts,"(30, 13)",0,objectid(long),0,355,0,0,0,0,TN,False
1,"(34, 0)",ff26cfb6b048749e7a435ed340d74230,Warden_Districts,"(30, 13)",0,objectid(long),1,356,0,0,0,0,TN,False
2,"(34, 0)",ff26cfb6b048749e7a435ed340d74230,Warden_Districts,"(30, 13)",0,objectid(long),2,357,0,0,0,0,TN,False
3,"(34, 0)",ff26cfb6b048749e7a435ed340d74230,Warden_Districts,"(30, 13)",0,objectid(long),3,358,0,0,0,0,TN,False
4,"(34, 0)",ff26cfb6b048749e7a435ed340d74230,Warden_Districts,"(30, 13)",0,objectid(long),4,359,0,0,0,0,TN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
874565,"(33, 0)",4f2c2cda8d02a7ff9adc99fc762206aa,Oregon_State_Government_Buildings,"(48, 24)",23,zip_four(double precision),43,3870.0,0,0,0,0,TN,False
874566,"(33, 0)",4f2c2cda8d02a7ff9adc99fc762206aa,Oregon_State_Government_Buildings,"(48, 24)",23,zip_four(double precision),44,4924.0,0,0,0,0,TN,False
874567,"(33, 0)",4f2c2cda8d02a7ff9adc99fc762206aa,Oregon_State_Government_Buildings,"(48, 24)",23,zip_four(double precision),45,3737.0,0,0,0,0,TN,False
874568,"(33, 0)",4f2c2cda8d02a7ff9adc99fc762206aa,Oregon_State_Government_Buildings,"(48, 24)",23,zip_four(double precision),46,1212.0,0,0,0,0,TN,False
874569,"(33, 0)",4f2c2cda8d02a7ff9adc99fc762206aa,Oregon_State_Government_Buildings,"(48, 24)",23,zip_four(double precision),47,1212.0,0,0,0,0,TN,False

In [60]:
average_f_score = {}
average_recall = {}
average_precision = {}
for e in [0, 1]:
    average_f_score[executions[e]] = {}
    average_recall[executions[e]] = {}
    average_precision[executions[e]] = {}
    for r in [0, 1, 2]:
        foo = results_per_table[executions[e]][runs[r]].T
        average_recall[executions[e]][r] = pd.DataFrame(results_per_table[executions[e]][runs[r]]).T["recall"].sum() / 96
        average_precision[executions[e]][r] = pd.DataFrame(results_per_table[executions[e]][runs[r]]).T["precision"].sum() / 96
        average_f_score[executions[e]][runs[r]] = pd.DataFrame(results_per_table[executions[e]][runs[r]]).T["f_score"].sum() / 96
average_f_score = pd.DataFrame(average_f_score)
average_recall = pd.DataFrame(average_recall)
average_precision = pd.DataFrame(average_precision)
average_f_score["diff"] = average_f_score["Integration_Option_1"] - average_f_score["Integration_Option_0"]
average_recall["diff"] = average_recall["Integration_Option_1"] - average_recall["Integration_Option_0"]
average_precision["diff"] = average_precision["Integration_Option_1"] - average_precision["Integration_Option_0"]
print("average_f_score")
display(average_f_score)
print("average_recall")
display(average_recall)
print("average_precision")
display(average_precision)

average_f_score

,Integration_Option_0,Integration_Option_1,diff
_test_edbt_DGov_Typo_192_labels,0.155003,0.240558,0.085555
_test_edbt_DGov_Typo_576_labels,0.297821,0.341643,0.043822
_test_edbt_DGov_Typo_1152_labels,0.366315,0.417795,0.051480

average_recall

   Integration_Option_0  Integration_Option_1      diff
0              0.200655              0.232415  0.031760
1              0.306957              0.341096  0.034138
2              0.365784              0.403863  0.038079

average_precision

   Integration_Option_0  Integration_Option_1      diff
0              0.149881              0.515056  0.365175
1              0.353386              0.591463  0.238076
2              0.425375              0.567962  0.142587

In [22]:
all_analysis = pd.DataFrame()
precision, recall, f_score= {}, {}, {}
for run in runs:
    precision[run[21:]], recall[run[21:]], f_score[run[21:]]= {}, {}, {}
    for execution in executions:
        result_df = result_dfs[execution][run]
        #result_df = result_df[result_df['table_name'] != "Rates_of_Preventable_Hospitalizations_for_Selected_Medical_Conditions_by_County_(LGHC_Indicator)"]
        analysis = result_df["result"].value_counts()
        if "TP" not in analysis: analysis["TP"] = 0
        if "FP" not in analysis: analysis["FP"] = 0
        if "TN" not in analysis: analysis["TN"] = 0
        if "FN" not in analysis: analysis["FN"] = 0

        analysis["precision"] = analysis["TP"] / (analysis["TP"] + analysis["FP"])
        analysis["recall"] = analysis["TP"] / (analysis["TP"] + analysis["FN"])
        analysis["F1 Score"] = 2 * (analysis["precision"] * analysis["recall"]) / (analysis["precision"] + analysis["recall"])
        precision[run[21:]][execution] = analysis["precision"]
        recall[run[21:]][execution] = analysis["recall"]
        f_score[run[21:]][execution] = analysis["F1 Score"]
        all_analysis[f"{run[21:]} - {execution}"] = analysis
display(all_analysis.T)
print("precision")
precision = pd.DataFrame(precision).T
precision["diff"] = precision[executions[1]] - precision[executions[0]]
display(pd.DataFrame(precision))
print("recall")
recall = pd.DataFrame(recall).T
recall["diff"] = recall[executions[1]] - recall[executions[0]]
display(pd.DataFrame(recall))
print("F1 Score")
f_score = pd.DataFrame(f_score).T
f_score["diff"] = f_score[executions[1]] - f_score[executions[0]]
display(pd.DataFrame(f_score))

result,TN,FN,TP,FP,precision,recall,F1 Score
192_labels - Integration_Option_0,566205.0,37744.0,26297.0,18000.0,0.593652,0.410628,0.485462
192_labels - Integration_Option_1,560028.0,36791.0,27250.0,24177.0,0.529877,0.425509,0.471992
576_labels - Integration_Option_0,566798.0,28904.0,35137.0,17407.0,0.668716,0.548664,0.602771
576_labels - Integration_Option_1,564656.0,28913.0,35128.0,19549.0,0.642464,0.548524,0.591789
1152_labels - Integration_Option_0,568095.0,24296.0,39745.0,16110.0,0.711575,0.620618,0.662991
1152_labels - Integration_Option_1,567726.0,24741.0,39300.0,16479.0,0.704566,0.613669,0.655984

precision

             Integration_Option_0  Integration_Option_1      diff
192_labels               0.593652              0.529877 -0.063775
576_labels               0.668716              0.642464 -0.026252
1152_labels              0.711575              0.704566 -0.007008

recall

             Integration_Option_0  Integration_Option_1      diff
192_labels               0.410628              0.425509  0.014881
576_labels               0.548664              0.548524 -0.000141
1152_labels              0.620618              0.613669 -0.006949

F1 Score

             Integration_Option_0  Integration_Option_1      diff
192_labels               0.485462              0.471992 -0.013470
576_labels               0.602771              0.591789 -0.010982
1152_labels              0.662991              0.655984 -0.007007

In [ ]:
result_dfs["Integration_Option_0"]["_test_edbt_DGov_Typo_192_labels"]

In [ ]:


final_results = {}
folder = "output/DGov_Typo_high_TP_ratio_0/_test_edbt_DGov_Typo_subsets/DGov_Typo_high_TP_ratio_30_labels/results/final_results"
files = os.listdir(folder)
files = sorted(files)
for file in files:
    path = os.path.join(folder, file)
    with open(path, "rb") as f:
        final_results[file] = pickle.load(f)

In [ ]:
for key in final_results:
    print(key)

In [ ]:
final_results["y_labeled_by_user_all.pickle"]

In [ ]:
os.listdir("/home/micro/Documents/Code/AutoMatelda/datasets/DGov_Typo_subsets/DGov_Typo_5")

In [ ]:
with open("output/DGov_Typo_high_TP_ratio_Integration_Option_0/_test_edbt_DGov_Typo_subsets/DGov_Typo_high_TP_ratio_10_labels/results/results_df.pickle", "rb") as f:
    results_df = pickle.load(f)
results_df

In [ ]:
import pandas as pd
auto_test_output_path = "/home/pavel/AutoTest/code/AutoTest/results/detected_outliers/combined_sdc_on_305b_Assessed_2008_Lake.csv"

auto_test_output_df = pd.read_table(auto_test_output_path, dtype=str)
if auto_test_output_df.columns == ',header,outlier,conf,dist_val,SDC':
    auto_test_output_df = pd.read_csv(auto_test_output_path, dtype=str)

In [ ]:
if auto_test_output_df.columns == 'header,outlier':
    print("true")
else:
    print("false")

In [ ]:
auto_test_config = {}
auto_test_config["rerun"] = True
auto_test_config["auto_test_path"] = "/home/pavel/AutoTest/code/AutoTest"
auto_test_config["sdc_file_name"] = "combined_sdc.csv"
auto_test_config["integration_pipeline_option"] = 0

import marshmallow_pipeline.auto_test.auto_test_util as autotest

foo = autotest.load_autotest_df(auto_test_config, "output/DGov_Typo_Integration_Option_0/_test_edbt_DGov_Typo_10_labels", "BLM_AZ_Travel_Management_Plans_(Polygon).csv")

In [ ]:
foo